# Generated by Django 6.0.2 on 2026-02-03 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='light', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('invoice_footer', models.TextField(blank=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_color', models.CharField(default='#263238', max_length=9)),
                ('locale', models.CharField(default='en_US', max_length=10)),
                ('tax_profiles', models.JSONField(default=list)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=100)),
                ('issuer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('issuer_title', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
